window.HAOYOUJI_MY_FIRST_HALF_DEMO = {
  id: "demo-my-first-half-v1",
  name: "《我的前半生》消费记录",
  startDate: "2017-07-03",
  endDate: "2017-11-24",
  people: [
    { id: "hehan", name: "贺涵", avatarIndex: 1 },
    { id: "tangjing", name: "唐晶", avatarIndex: 15 },
    { id: "luozijun", name: "罗子君", avatarIndex: 14 },
    { id: "chenjunsheng", name: "陈俊生", avatarIndex: 12 },
    { id: "lingling", name: "凌玲", avatarIndex: 5 },
    { id: "xuezhenzhu", name: "薛甄珠", avatarIndex: 20 },
    { id: "wudaniang", name: "吴大娘", avatarIndex: 17 },
    { id: "laozhuo", name: "老卓", avatarIndex: 3 }
  ],
  expenses: [
    { title: "陈俊生大手笔买下定制小羊皮高跟鞋送给前妻，自己压根没有穿高跟鞋的机会", date: "2017-07-03", category: "借用", participants: ["罗子君"], currency: "CNY", amount: 80000, payer: "陈俊生", note: "婚姻存续期赠与消费" },
    { title: "贺涵购入日本筑地市场直采空运蓝鳍金枪鱼大腹刺身，后续邀约唐晶进店一同享用", date: "2017-07-05", category: "餐饮", participants: ["贺涵"], currency: "JPY", amount: 780000, payer: "贺涵", note: "日本竞拍采购，日元结算，后续与唐晶分享" },
    { title: "专门从欧洲产地空运顶级鲟鱼黑鱼子酱配送至酱子，仅贺涵专属预定，未与任何人分享", date: "2017-07-05", category: "餐饮", participants: ["贺涵"], currency: "USD", amount: 4200, payer: "贺涵", note: "欧洲采购，美元结算，后期用来对峙" },
    { title: "贺涵约唐晶酱子约会聚餐，共享空运蓝鳍金枪鱼，本该浪漫约会，二人全程聊着行业项目，硬生生把情侣局开成小型工作会议", date: "2017-07-08", category: "餐饮", participants: ["贺涵", "唐晶"], currency: "CNY", amount: 1800, payer: "贺涵", note: "情侣约会，食用此前空运金枪鱼" },
    { title: "家庭聚餐直接拿下包厢，支付包厢服务费，菜品多点不怕剩，排场直接拉满", date: "2017-07-10", category: "餐饮", participants: ["陈俊生", "罗子君", "薛甄珠"], currency: "CNY", amount: 2280, payer: "陈俊生", note: "离婚前最后一次全家聚餐" },
    { title: "入手上海静安华侨城苏河湾独栋大别墅，全屋硬装软装配齐拎包入住，豪华居所安心自住", date: "2017-07-12", category: "酒店", participants: ["贺涵"], currency: "CNY", amount: 90000000, payer: "贺涵", note: "贺涵购置房产" },
    { title: "迫于尴尬处境，在前妻上班鞋店买皮鞋送给现任凌玲，顺带帮前妻冲一波门店业绩", date: "2017-07-14", category: "借用", participants: ["凌玲"], currency: "CNY", amount: 10500, payer: "陈俊生", note: "正式摊牌当日，陈俊生给凌玲消费，婚姻矛盾爆发" },
    { title: "家常小饭馆简单用餐，饭桌上拉扯离婚琐事，一顿饭吃得各怀心事", date: "2017-07-17", category: "餐饮", participants: ["薛甄珠", "罗子君", "陈俊生"], currency: "CNY", amount: 360, payer: "陈俊生", note: "离婚谈判初期拉扯" },
    { title: "几位主角意外在饭馆碰面，一桌之内新旧关系齐聚，堪称大型尴尬社交现场", date: "2017-08-02", category: "餐饮", participants: ["罗子君", "陈俊生", "凌玲", "唐晶", "贺涵"], currency: "CNY", amount: 1250, payer: "贺涵", note: "离婚矛盾激化，众人偶遇碰面" },
    { title: "深夜相约日料店宵夜，几个中年男士喝酒闲聊，吐槽各自生活烦心事", date: "2017-08-10", category: "餐饮", participants: ["陈俊生", "贺涵", "老卓"], currency: "CNY", amount: 750, payer: "贺涵", note: "陈俊生倾诉再婚烦恼" },
    { title: "唐晶下班避开社交，一人安静享用日料，享受无人打扰的独处时光", date: "2017-08-16", category: "餐饮", participants: ["唐晶"], currency: "CNY", amount: 780, payer: "唐晶", note: "唐晶独处休闲" },
    { title: "陈俊生与凌玲低调晚间约会，选择普通餐厅简单吃饭，褪去阔绰模样", date: "2017-08-20", category: "餐饮", participants: ["陈俊生", "凌玲"], currency: "CNY", amount: 420, payer: "陈俊生", note: "婚后日常简约约会" },
    { title: "罗子君人生低谷时期，贺涵带着她吃西餐开导心情，一边吃饭一边疏导情绪", date: "2017-08-28", category: "餐饮", participants: ["贺涵", "罗子君"], currency: "CNY", amount: 920, payer: "贺涵", note: "罗子君刚入职超市受挫，贺涵开导" },
    { title: "老牌小笼包铺子吃早餐，两位女生边吃点心唠家常，烟火气十足", date: "2017-09-02", category: "餐饮", participants: ["罗子君", "唐晶"], currency: "CNY", amount: 186, payer: "罗子君", note: "唐晶陪伴失业低谷的罗子君" },
    { title: "超市采购火锅食材，两个女生回出租屋涮火锅，自在放松随心吃喝", date: "2017-09-08", category: "便利店", participants: ["罗子君", "唐晶"], currency: "CNY", amount: 290, payer: "罗子君", note: "罗子君做超市收银员阶段，闺蜜聚餐" },
    { title: "外滩望江阁预定私密双人西餐，牛排前菜饮品配齐，坐拥绝美夜景，二人照旧抽空探讨职场局势，浪漫氛围掺满职场味道", date: "2017-09-16", category: "餐饮", participants: ["唐晶", "贺涵"], currency: "CNY", amount: 1600, payer: "唐晶", note: "贺唐二人晚间约会" },
    { title: "单独支付观景席位费用，坐拥整片外滩夜景，氛围感直接拉满", date: "2017-09-16", category: "娱乐", participants: ["唐晶", "贺涵"], currency: "CNY", amount: 880, payer: "唐晶", note: "外滩观景额外消费" },
    { title: "贺涵临时动身前往香港，上海香港往返国泰商务舱全价机票，从来不蹲打折机票", date: "2017-10-08", category: "机票", participants: ["贺涵"], currency: "CNY", amount: 12800, payer: "贺涵", note: "贺涵香港出差" },
    { title: "香港海边海景餐厅碰面吃饭，异地相聚共进晚餐，聊着聊着又复盘起手上的合作项目", date: "2017-10-10", category: "餐饮", participants: ["唐晶", "贺涵"], currency: "HKD", amount: 2020, payer: "贺涵", note: "香港会面就餐，港币结算" },
    { title: "商圈咖啡馆下午茶落座，职场前辈边喝咖啡，传授打工生存干货", date: "2017-10-22", category: "餐饮", participants: ["吴大娘", "罗子君"], currency: "CNY", amount: 260, payer: "吴大娘", note: "罗子君鞋店做销冠，结识吴大娘铺垫跳槽" },
    { title: "商务饭局安排高档饭店，前辈带着新人饭桌社交，拓展人脉洽谈合作", date: "2017-10-28", category: "餐饮", participants: ["吴大娘", "罗子君"], currency: "CNY", amount: 1480, payer: "吴大娘", note: "罗子君进入咨询行业初期商务局" },
    { title: "菜市场采购新鲜荤素食材，唐晶亲自下厨招待朋友，居家聚餐更显心意", date: "2017-11-05", category: "便利店", participants: ["唐晶", "贺涵", "罗子君"], currency: "CNY", amount: 450, payer: "唐晶", note: "三人关系微妙阶段居家聚餐" },
    { title: "高端女装专柜选购成衣，定制多套职场西装配饰，打造干练职场穿搭造型", date: "2017-11-12", category: "购物", participants: ["唐晶"], currency: "CNY", amount: 28600, payer: "唐晶", note: "唐晶职场着装添置" },
    { title: "升职加薪之后主动请客吃饭，答谢前辈一路提携照顾，做人讲究人情世故", date: "2017-11-15", category: "餐饮", participants: ["罗子君", "吴大娘"], currency: "CNY", amount: 330, payer: "罗子君", note: "罗子君正式升职，最终成长节点，时间跨度4个月，成长节奏合理" },
    { title: "几人在日料店偶然撞上，干脆拼桌同席吃饭，场面微妙又热闹", date: "2017-11-20", category: "餐饮", participants: ["贺涵", "唐晶", "罗子君", "吴大娘"], currency: "CNY", amount: 1600, payer: "贺涵", note: "升职后的众人碰面聚餐" },
    { title: "本帮菜馆设宴招待长辈，礼貌陪同用餐，兼顾礼数与体面", date: "2017-11-22", category: "餐饮", participants: ["薛甄珠", "贺涵", "罗子君"], currency: "CNY", amount: 1380, payer: "贺涵", note: "罗子君事业稳定后陪母亲吃饭" },
    { title: "用餐结束后贺涵预约携程行政豪华专车陪同薛甄珠坐车前往百乐门跳舞，体面安排出行行程", date: "2017-11-22", category: "打车", participants: ["薛甄珠", "贺涵"], currency: "CNY", amount: 198, payer: "贺涵", note: "饭后护送薛甄珠出行" },
    { title: "购入美术馆双人门票，空闲时间结伴看展散心，打发闲暇时光", date: "2017-11-24", category: "门票", participants: ["罗子君", "唐晶"], currency: "CNY", amount: 220, payer: "罗子君", note: "两位女生休闲看展" }
  ]
};
